CREATE TABLE [dbo].[Cars]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[OwnerId] NVARCHAR(100) NOT NULL,
	[ForSale] BIT NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[Manufacturer] NVARCHAR(50) NOT NULL,
	[Bodywork] NVARCHAR(20) NOT NULL,
	[Color] NVARCHAR(20) NOT NULL,
	[EngineType] NVARCHAR(50) NULL,
	[HorsePower] NVARCHAR(20) NULL,
	[Mileage] NVARCHAR(20) NOT NULL,
	[CarState] NVARCHAR(20) NULL,
	[Price] NVARCHAR(50) NULL
)
