CREATE TABLE [dbo].[Images]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[CarId] INT NOT NULL,
	CONSTRAINT FK_Images_CarId FOREIGN KEY (CarId) REFERENCES Cars(Id),
	[Path] NVARCHAR(100),
	[IsHeadPhoto] BIT NOT NULL
)
