CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[UserName] NVARCHAR(50) NOT NULL,
	[PassWord] NVARCHAR(50) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(50) NULL,
	[Email] NVARCHAR(50) NOT NULL,
	[PhoneNumber] NVARCHAR(50) NULL,
	[Role] NVARCHAR(50) NOT NULL
)
